// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Company struct {
	CompanyID            int32          `json:"company_id"`
	Name                 string         `json:"name"`
	Website              sql.NullString `json:"website"`
	Industry             sql.NullString `json:"industry"`
	Description          sql.NullString `json:"description"`
	HeadquartersLocation sql.NullString `json:"headquarters_location"`
	FoundedYear          sql.NullInt32  `json:"founded_year"`
	IsPublic             sql.NullBool   `json:"is_public"`
	TickerSymbol         sql.NullString `json:"ticker_symbol"`
	ScrapeTimestamp      sql.NullTime   `json:"scrape_timestamp"`
}

type CompanyNews struct {
	NewsID          int32          `json:"news_id"`
	CompanyID       sql.NullInt32  `json:"company_id"`
	Title           string         `json:"title"`
	PublicationDate sql.NullTime   `json:"publication_date"`
	Source          sql.NullString `json:"source"`
	Url             sql.NullString `json:"url"`
	Summary         sql.NullString `json:"summary"`
	Sentiment       sql.NullString `json:"sentiment"`
	DatasourceID    sql.NullInt32  `json:"datasource_id"`
}

type Contact struct {
	ContactID       int32          `json:"contact_id"`
	FirstName       sql.NullString `json:"first_name"`
	LastName        sql.NullString `json:"last_name"`
	Email           sql.NullString `json:"email"`
	Phone           sql.NullString `json:"phone"`
	LinkedinProfile sql.NullString `json:"linkedin_profile"`
	JobTitle        sql.NullString `json:"job_title"`
	CompanyID       sql.NullInt32  `json:"company_id"`
	Location        sql.NullString `json:"location"`
	Bio             sql.NullString `json:"bio"`
	ScrapeTimestamp sql.NullTime   `json:"scrape_timestamp"`
}

type ContactNews struct {
	MentionID       int32          `json:"mention_id"`
	ContactID       sql.NullInt32  `json:"contact_id"`
	Title           string         `json:"title"`
	PublicationDate sql.NullTime   `json:"publication_date"`
	Source          sql.NullString `json:"source"`
	Url             sql.NullString `json:"url"`
	Summary         sql.NullString `json:"summary"`
	DatasourceID    sql.NullInt32  `json:"datasource_id"`
}

type Datasource struct {
	DatasourceID        int32         `json:"datasource_id"`
	SourceType          string        `json:"source_type"`
	SourceID            sql.NullInt32 `json:"source_id"`
	ExtractionTimestamp sql.NullTime  `json:"extraction_timestamp"`
}

type MatchingScoreCriterium struct {
	CriteriaID  int32          `json:"criteria_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Weight      string         `json:"weight"`
}

type Paragraph struct {
	ParagraphID     int32          `json:"paragraph_id"`
	DatasourceID    sql.NullInt32  `json:"datasource_id"`
	Content         string         `json:"content"`
	MainIdea        sql.NullString `json:"main_idea"`
	Classification  sql.NullString `json:"classification"`
	ConfidenceScore sql.NullString `json:"confidence_score"`
}

type Project struct {
	ProjectID     int32          `json:"project_id"`
	UserID        sql.NullInt32  `json:"user_id"`
	ProjectName   string         `json:"project_name"`
	Description   sql.NullString `json:"description"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	LastUpdatedAt sql.NullTime   `json:"last_updated_at"`
}

type ProjectCompany struct {
	ProjectID        int32          `json:"project_id"`
	CompanyID        int32          `json:"company_id"`
	AssociationNotes sql.NullString `json:"association_notes"`
	MatchingScore    sql.NullString `json:"matching_score"`
	ApproachStrategy sql.NullString `json:"approach_strategy"`
}

type ProjectContact struct {
	ProjectID        int32          `json:"project_id"`
	ContactID        int32          `json:"contact_id"`
	AssociationNotes sql.NullString `json:"association_notes"`
}

type ProjectFile struct {
	FileID     int32         `json:"file_id"`
	ProjectID  sql.NullInt32 `json:"project_id"`
	FileName   string        `json:"file_name"`
	FileType   string        `json:"file_type"`
	FilePath   string        `json:"file_path"`
	UploadedAt sql.NullTime  `json:"uploaded_at"`
	FileSize   sql.NullInt32 `json:"file_size"`
}

type User struct {
	UserID       int32        `json:"user_id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
