// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    user_id, project_name, main_idea
)
VALUES ($1, $2, $3)
RETURNING project_id, user_id, project_name, main_idea, created_at, updated_at
`

type CreateProjectParams struct {
	UserID      int32          `json:"user_id"`
	ProjectName string         `json:"project_name"`
	MainIdea    sql.NullString `json:"main_idea"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.UserID, arg.ProjectName, arg.MainIdea)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.ProjectName,
		&i.MainIdea,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE project_id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, projectID int32) error {
	_, err := q.db.ExecContext(ctx, deleteProject, projectID)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT project_id, user_id, project_name, main_idea, created_at, updated_at
FROM projects
WHERE project_id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, projectID int32) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, projectID)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.ProjectName,
		&i.MainIdea,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByUserID = `-- name: ListProjectsByUserID :many
SELECT project_id, user_id, project_name, main_idea, created_at, updated_at
FROM projects
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectsByUserIDParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProjectsByUserID(ctx context.Context, arg ListProjectsByUserIDParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.ProjectName,
			&i.MainIdea,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProjectsByName = `-- name: SearchProjectsByName :many
SELECT project_id, user_id, project_name, main_idea, created_at, updated_at
FROM projects
WHERE user_id = $1 AND project_name ILIKE '%' || $2 || '%'
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type SearchProjectsByNameParams struct {
	UserID  int32          `json:"user_id"`
	Column2 sql.NullString `json:"column_2"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) SearchProjectsByName(ctx context.Context, arg SearchProjectsByNameParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, searchProjectsByName,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.ProjectName,
			&i.MainIdea,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET project_name = $2,
    main_idea = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE project_id = $1
RETURNING project_id, user_id, project_name, main_idea, created_at, updated_at
`

type UpdateProjectParams struct {
	ProjectID   int32          `json:"project_id"`
	ProjectName string         `json:"project_name"`
	MainIdea    sql.NullString `json:"main_idea"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.ProjectID, arg.ProjectName, arg.MainIdea)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.ProjectName,
		&i.MainIdea,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
